-- DQL : DATA QUERY LANGUAGE
-- SELECT

-- DML : DATA MANIPULATION LANGUAGE
-- INSERT, UPDATE, DELETE

-- DDL : DATA DEFINITION LANGUAGE
-- CREATE, DESCRIBE, ALTER, DROP

-- SCHEMA -- ESTRUCTURA DE LA BASE DE DATOS
-- TABLES, COLUMNS, CONSTRAINTS, INDEXES, SEQUENCE, VIEWS

CREATE TABLE PERSONA (
  id_per NUMBER,
  name VARCHAR(100),
  email VARCHAR(200)
);

CREATE TABLE AUTOMOVIL (
  id_aut NUMBER,
  model VARCHAR(100),
  brand VARCHAR(100),
  id_per NUMBER
);

DESCRIBE PERSONA;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'PERSONA';

DESCRIBE AUTOMOVIL;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'AUTOMOVIL';

INSERT INTO PERSONA (id_per, name, email) VALUES (1, 'JUAN', 'JUAN@GMAIL.COM');
INSERT INTO PERSONA (id_per, name, email) VALUES (2, 'LUIS', 'LUIS@GMAIL.COM');
INSERT INTO PERSONA (id_per, name, email) VALUES (3, 'PEPE', 'PEPE@GMAIL.COM');
INSERT INTO PERSONA (id_per, name, email) VALUES (4, 'JOSE', 'JOSE@GMAIL.COM');
INSERT INTO PERSONA (id_per, name, email) VALUES (5, 'HANA', 'HANA@GMAIL.COM');
INSERT INTO PERSONA (id_per, name, email) VALUES (6, 'TONY', 'TONY@GMAIL.COM');
INSERT INTO PERSONA (id, name, email) VALUES (7, 'LILY', 'LILY@GMAIL.COM');

DELETE PERSONA WHERE id_per=6;

TRUNCATE TABLE PERSONA;
SELECT * FROM PERSONA;

INSERT INTO AUTOMOVIL VALUES (1, 'COROLA', 'TOYOTA', 1);
INSERT INTO AUTOMOVIL VALUES (2, 'SAIL', 'CHEVROLET', 2);
INSERT INTO AUTOMOVIL VALUES (3, 'SPARK', 'FORD', 3);
INSERT INTO AUTOMOVIL VALUES (4, 'VITARA', 'FORD', 4);
INSERT INTO AUTOMOVIL VALUES (5, 'CHINITO', 'CHINA', 5);
INSERT INTO AUTOMOVIL VALUES (6, 'CHILENITO', 'CHICHI', 6);
INSERT INTO AUTOMOVIL VALUES (7, 'PERUANITO', 'PERU', 7);

UPDATE AUTOMOVIL SET id_per=6 WHERE id_aut=6;
DELETE AUTOMOVIL WHERE id_aut=6;

SELECT * FROM AUTOMOVIL;

ALTER TABLE PERSONA ADD CONSTRAINT id_per_pk PRIMARY KEY (id_per);
ALTER TABLE PERSONA MODIFY email UNIQUE;

ALTER TABLE PERSONA DROP CONSTRAINT SYS_C0021199;
ALTER TABLE PERSONA ADD CONSTRAINT email_un UNIQUE (email);

ALTER TABLE AUTOMOVIL ADD CONSTRAINT id_aut_pk PRIMARY KEY (id_aut);
ALTER TABLE AUTOMOVIL ADD CONSTRAINT id_per_fk FOREIGN KEY (id_per) REFERENCES PERSONA (id_per);

ALTER TABLE AUTOMOVIL DROP CONSTRAINT id_per_fk;

ALTER TABLE AUTOMOVIL ADD CONSTRAINT id_per_fk 
FOREIGN KEY (id_per) REFERENCES PERSONA (id_per)
ON DELETE CASCADE;

ALTER TABLE AUTOMOVIL ADD CONSTRAINT id_per_fk 
FOREIGN KEY (id_per) REFERENCES PERSONA (id_per)
ON DELETE SET NULL;

ALTER TABLE PERSONA DROP COLUMN id_per CASCADE CONSTRAINTS;

ALTER TABLE PERSONA ADD id_per NUMBER;

ALTER TABLE PERSONA RENAME COLUMN id_per TO id; 
ALTER TABLE PERSONA RENAME TO PERSON;

CREATE SYNONYM PERSONA FOR PERSON;
SELECT * FROM PERSON;

ALTER TABLE AUTOMOVIL DISABLE CONSTRAINT id_per_fk;
ALTER TABLE AUTOMOVIL ENABLE CONSTRAINT id_per_fk;
