DESCRIBE DICTIONARY;
SELECT * FROM DICTIONARY;

SELECT * FROM DICTIONARY WHERE table_name LIKE 'USER_%';

SELECT * FROM USER_OBJECTS WHERE object_type = 'TABLE';
SELECT * FROM USER_TABLES;

SELECT * FROM ALL_OBJECTS WHERE object_type = 'TABLE' AND owner = 'ORA22';
SELECT * FROM ALL_TABLES WHERE owner = 'ORA22';

SELECT * FROM USER_TAB_COLUMNS WHERE table_name = 'LOCATIONS';

SELECT * FROM USER_CONSTRAINTS;
DESCRIBE USER_CONSTRAINTS;

SELECT column_name FROM USER_TAB_COLUMNS WHERE table_name = 'EMPLOYEES';
INSERT INTO USER_OBJECTS (OBJECT_NAME) VALUES ('TEST');
DESCRIBE USER_OBJECTS;

DESCRIBE COUNTRIES;
DESCRIBE USER_TABLES;
